delete page
mayu0506/freemarket_sample_50dn pull request #105
Opened 2019-05-18 10:57 UTC by pon182

[what]
deleteページ
商品の削除機能

[why]
商品を削除する為必須機能

2019-05-18 11:06 UTC, mayu0506 commented on config/routes.rb
> +    get :delete
上でdestroyアクション定義されているのでdeleteはいらないのではないでしょうか？

2019-05-18 12:16 UTC, miyagit commented on app/views/products/delete.html.haml
> +    =image_tag "#{@image.image}",width: 400
=のあとは一つスペースあったほうが可読性あがりますね。

2019-05-18 12:16 UTC, miyagit commented on config/routes.rb
> +  resources :products, only: [:index, :new, :create, :show, :edit ,:destroy] do
:edit ,になってるので修正しましょう。

2019-05-19 03:24 UTC, nagatomokent commented on app/views/products/delete.html.haml
> +    =image_tag "#{@image.image}",width: 400
こちら修正お願いします
また、他の部分も修正お願いします

2019-05-19 03:24 UTC, nagatomokent commented on config/routes.rb
> +    get :delete
不要ですね

2019-05-19 03:27 UTC, nagatomokent commented
コメント返したので修正お願いします

2019-05-19 04:02 UTC, pon182 commented on app/views/products/delete.html.haml
> +    =image_tag "#{@image.image}",width: 400
失礼いたしました。
修正いたしました。

2019-05-19 04:04 UTC, pon182 commented on config/routes.rb
> +    get :delete
deleteというviewページを作ってしまっていた為
相違が起こってしまい申し訳ございません。

名前を変更いたしました。

2019-05-19 06:07 UTC, ghost requested changes

2019-05-19 06:07 UTC, hiroki5123 commented on app/views/products/change.html.haml
> +    = image_tag "#{@image.image}",width: 400
widthはCSS側に指定しましょう

2019-05-19 07:57 UTC, pon182 commented on app/views/products/change.html.haml
> +    = image_tag "#{@image.image}",width: 400
変更いたしました。
よろしくお願いいたします。

2019-05-19 08:01 UTC, kuroko918 commented on config/routes.rb
> +  resources :products, only: [:index, :new, :create, :show, :edit, :destroy] do
rootにindex指定してあるのでここの、indexは不要ですね！

2019-05-19 08:07 UTC, pon182 commented on config/routes.rb
> +  resources :products, only: [:index, :new, :create, :show, :edit, :destroy] do
削除しました。

2019-05-19 08:09 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-05-19 08:10 UTC, ghost approved these changes
LGTMです！

2019-05-19 08:17 UTC, pon182 commented
ありがとうございました！

2019-05-19 08:17 UTC, merged